repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.5.4
      hooks:
          - id: aoc-tiles
            # Optionally use these arguments. Auto add tiles to git adds the tiles to git,
            # possibly amends your commit by creating the tile images and updating the README.
            # Language sorting shows the preference of the order of the languages to use.
            # Exclude patterns are globs which can be used to exclude files when creating
            # the tiles. See the customization section in the README for more flags.
            # Simply remove the comments (#) below for args and the flags you want.
            args:
                - --auto-add-tiles-to-git=amend
                - --create-all-days
                - --contrast-improvement-type=dark
                - --contrast-improvement-threshold=255
            #     - --language-sorting=jl,kt,py,rs
